=== heiglandreas/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://heigl.org/holidays"
           xmlns="https://heigl.org/holidays"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynamelist">
        <xs:list itemType="daynames" />
    </xs:simpleType>
    <xs:simpleType name="calendars">
        <xs:restriction base="xs:string">
            <xs:enumeration value="buddhist"/>
            <xs:enumeration value="chinese"/>
            <xs:enumeration value="coptic"/>
            <xs:enumeration value="ethiopian"/>
            <xs:enumeration value="gregorian"/>
            <xs:enumeration value="hebrew"/>
            <xs:enumeration value="indian"/>
            <xs:enumeration value="islamic"/>
            <xs:enumeration value="islamic-civil"/>
            <xs:enumeration value="islamic-umalqura"/>
            <xs:enumeration value="islamic-rgsa"/>
            <xs:enumeration value="islamic-tbla"/>
            <xs:enumeration value="japanese"/>
            <xs:enumeration value="persian"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="replaced" type="daynamelist" use="optional" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
        <xs:attribute name="previous" type="daynames" use="optional"/>
        <xs:attribute name="previouswhen" type="daynamelist" use="optional"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="resourceAttributes">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
        <xs:attribute name="lastChecked" type="xs:date" use="required" />
    </xs:attributeGroup>
    <xs:attributeGroup name="forward">
        <xs:attribute name="forwardto" type="daynames" use="optional"/>
        <xs:attribute name="forwardwhen" type="daynamelist" use="optional" />
    </xs:attributeGroup>
    <xs:attributeGroup name="rewind">
        <xs:attribute name="rewindto" type="daynames" use="optional"/>
        <xs:attribute name="rewindwhen" type="daynamelist" use="optional" />
    </xs:attributeGroup>
    <xs:element name="resources">

    </xs:element>
    <xs:element name="holidays">
        <!--
        All elements have to be within the root element "holidays".

        Within this root element we expect a list of entries of type
        "easter", "easterorthodox", "date", "dateFollowUp" or "relative"

        Explanations follow on the respective elements
        -->
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="resources" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attributeGroup ref="resourceAttributes"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easter" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are relative to the Easter date as calculated for the
                    Western christian churches. The actual day is referenced by an
                    offset from easter-sunday. Days before easter sunday have a
                    negative offset, days after have a positive offset
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easterorthodox" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are relative to the Easter date as calculated for the
                    Eastern Christian churches. The actual day is referenced by an
                    offset from easter-sunday. Days before easter sunday have a
                    negative offset, days after have a positive offset
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are defined by their actual date like the 4th of July
                    or 25th of December.

                    The actual day is referenced by at least a day and a month attribute.
                    For special occasions where a day is only a holiday in a certain year
                    it can also have a year attribute. Note that you will need multiple
                    entries for multiple years.
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateAttributes"/>
                                <xs:attributeGroup ref="rewind"/>
                                <xs:attributeGroup ref="forward"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateFollowUp" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateFollowUpAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    This is similar to the dateFollowUp but the relation can be
                    more complext.

                    Again the date the relation is referenced from is given via
                    day and month attributes but the relation itself is given in
                    the relation attribute and can be anything that
                    http://php.net/manual/de/datetimeimmutable.modify.php
                    can handle. Like "last sunday -3 weeks" from 25th of december
                    would be the 1st sunday in advent
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="relativeAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== heiglandreas/holidayChecker/share/PY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Paraguay" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true" comment="New Year">Ano Nuevo</date>
	<date day="1" month="3" free="true" comment="National Heroes Day">Dia de los héroes</date>
	<easter offset="-4" free="true" comment="Maundy Thursday">Jueves Santo</easter>
	<easter offset="-3" free="true" comment="Good Friday">Viernes Santo</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Día de los Trabajadores</date>
	<date day="14" month="5" free="true" comment="Independence Day">Dia de la Independencia</date>
	<date day="12" month="6" free="true" comment="Chaco Armistice Day">Dia de la Paz del Chaco</date>
	<date day="15" month="8" free="true" comment="Foundation of Asunción">Fundación de Asunción</date>
	<date day="29" month="9" free="true" comment="Battle of Boqueron">Victoria de Boquerón</date>
	<date day="8" month="12" free="true" comment="Virgin of Caacupe">Virgen de Caacupé</date>
	<date day="25" month="12" free="true"	comment="Christmas Day">Día de Navidad</date>
</holidays>

=== heiglandreas/holidayChecker/share/GY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Guyana" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true">New Year's Day</date>
	<date day="23" month="2" free="true">Republic Day</date>
	<date day="15" month="12" free="true" calendar="indian">Phagwah</date>
	<easter offset="-2" free="true">Good Friday</easter>
	<easter offset="1" free="true">Easter Monday</easter>
	<date day="1" month="5" free="true">Labour</date>
	<date day="5" month="5" free="true">Arrival Day</date>
	<date day="26" month="5" free="true">Independence Day</date>
	<relative day="30" month="6" relation="next Monday" free="true">CARICOM Day</relative>
	<date day="1" month="8" free="true">Emancipation Day</date>
	<date day="27" month="7" free="true" calendar="indian">Diwali</date>
	<date day="25" month="12" free="true">Christmas Day</date>
	<date day="26" month="12" free="true">Boxing Day</date>
	<date day="12" month="3" free="true" calendar="islamic-civil">Youman-Nabi</date>
	<date day="15" month="3" free="true" calendar="islamic-civil">Youman-Nabi</date>
	<date day="10" month="12" free="true" calendar="islamic-civil">Eid-ul-Adha</date>
</holidays>

=== heiglandreas/holidayChecker/share/CL.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Chile" lastChecked="2022-10-27">Wikipedia</resource>
    </resources>
    <date day="1" month="1" free="true" comment="New Year's Day">Año Nuevo</date>
		<easter offset="-2" free="true" comment="Good Friday">Viernes Santo</easter>
		<easter offset="-1" free="true" comment="Holy Saturday">Sábado Santo</easter>
    <date day="1" month="5" free="true" comment="Labour Day">Día del Trabajo</date>
    <date day="21" month="5" free="true" comment="Navy Day">Día de las Glorias Navales</date>
    <date day="7" month="6" free="true" comment="Battle of Arica">Asalto y Toma del Morro de Arica</date>
    <date day="21" month="6" free="true" comment="National Day of Aboriginal Peoples">Día Nacional de los Pueblos Indígenas</date>
    <date day="27" month="6" forwardto="monday" forwardwhen="tuesday wednesday thursday" rewindto="monday" rewindwhen="friday" free="true" comment="Saint Peter and Saint Paul">San Pedro y San Pablo</date>
    <date day="16" month="7" forwardto="monday" forwardwhen="tuesday wednesday thursday" rewindto="monday" rewindwhen="friday" free="true" comment="Our Lady of Mount Carmel">Virgen del Carmen</date>
    <date day="15" month="8" free="true" comment="Assumption of Mary">Asunción de la Virgen</date>
    <date day="20" month="8" free="true" comment="Nativity of Liberator Bernardo O'Higgins">Nacimiento del Prócer de la Independencia</date>
    <date day="4" month="9" free="true" comment="National plebiscite">Plebiscito nacional</date>
    <date day="18" month="9" free="true" comment="National Day">Fiestas Patrias</date>
    <date day="19" month="9" free="true" comment="Army Day">Día de las Glorias del Ejército</date>
    <date day="12" month="10" forwardto="monday" forwardwhen="tuesday wednesday thursday" rewindto="monday" rewindwhen="friday" free="true" comment="Columbus Day">Día de las Glorias del Ejército</date>
    <date day="31" month="10" free="true" comment="Reformation Day">Día Nacional de las Iglesias Evangélicas y Protestantes</date>
    <date day="1" month="11" free="true" comment="All Saints">Día de Todos los Santos</date>
    <date day="8" month="12" free="true" comment="Immaculate Conception">Inmaculada Concepción</date>
    <date day="25" month="12" free="true" comment="Christmas Day">Navidad / Natividad del Señor</date>
</holidays>

=== heiglandreas/holidayChecker/share/DE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://www.heigl.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.heigl.org holidays.xsd"
>
    <date day="1" month="1" free="true">Neujahr</date>
    <date day="6" month="1" free="false">Epiphanias</date>
    <easter offset="-2" free="true">Karfreitag</easter>
    <easter offset="1" free="true">Ostermontag</easter>
    <easter offset="0" free="false">Ostersonntag</easter>
    <date day="1" month="5" free="true">Maifeiertag</date>
    <easter offset="49" free="false">Pfingstsonntag</easter>
    <easter offset="50" free="true">Pfingstmontag</easter>
    <easter offset="39" free="true">Christi Himmelfahrt</easter>
    <easter offset="60" free="false">Fronleichnam</easter>
    <date day="15" month="8" free="false">Mariä Himmelfahrt</date>
    <date day="3" month="10" free="true">Tag d. Dt. Einheit</date>
    <date day="31" month="10" year="2017" free="true">Reformationstag</date>
    <date day="31" month="10" free="false">Reformationstag</date>
    <date day="1" month="11" free="false">Allerheiligen</date>
    <relative day="23" month="11" free="false" relation="last wednesday">Buß- und Bettag</relative>
    <relative day="25" month="12" free="false" relation="last sunday -3 weeks">1. Advent</relative>
    <relative day="25" month="12" free="false" relation="last sunday -2 weeks">2. Advent</relative>
    <relative day="25" month="12" free="false" relation="last sunday -1 weeks">3. Advent</relative>
    <relative day="25" month="12" free="false" relation="last sunday">4. Advent</relative>
    <date day="24" month="12" free="false">Heilig Abend</date>
    <date day="25" month="12" free="true">1. Weihnachtstag</date>
    <date day="26" month="12" free="true">2. Weihnachtstag</date>
    <date day="31" month="12" free="false">Silvester</date>
</holidays>

=== heiglandreas/holidayChecker/share/US.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/holidays https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">New Year's Day</date>
    <relative day="1" month="1" relation="third monday of this month" free="true">Birthday of Martin Luther King, Jr.</relative>
    <relative day="1" month="2" relation="third monday of this month" free="true">Washington's Birthday</relative>
    <relative day="1" month="5" relation="last monday of this month" free="true">Memorial Day</relative>
    <date day="4" month="7" free="true">Independence Day</date>
    <relative day="1" month="9" relation="first monday of this month" free="true">Labor Day</relative>
    <relative day="1" month="10" relation="second monday of this month" free="true">Columbus Day</relative>
    <date day="11" month="11" free="true">Veterans Day</date>
    <relative day="1" month="11" relation="fourth thursday of this month" free="true">Thanksgiving Day</relative>
    <date day="25" month="12" free="true">Christmas Day</date>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Federal_holidays_in_the_United_States" lastChecked="2020-12-27">
            Wikipedia
        </resource>
    </resources>
</holidays>

=== heiglandreas/holidayChecker/share/PE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Peru" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true" comment="New Years Day">Año Nuevo</date>
	<easter offset="-3" free="true" comment="Maundy Thursday">Jueves Santo</easter>
	<easter offset="-2" free="true" comment="Good Friday">Viernes Santo</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Día del Trabajo</date>
	<date day="7" month="6" free="true" comment="Flag Day">Día de la Bandera</date>
	<date day="29" month="6" free="true" comment="Peter and Paul">San Pedro y San Pablo</date>
	<date day="23" month="7" free="true" comment="AirForce Day">Día de la Fuerza Aérea</date>
	<date day="28" month="7" free="true" comment="Independence Day">Día de la Independencia</date>
	<date day="29" month="7" free="true" comment="Independence Day">Día de la Independencia</date>
	<date day="6" month="8" free="true" comment="Battle of Junin">Batalla de Junin</date>
	<date day="30" month="8" free="true" comment="Santa Rosa de Lima">Día de Santa Rosa de Lima</date>
	<date day="8" month="10" free="true" comment="Battle of Angamos">Combate de Angamos</date>
	<date day="1" month="11" free="true" comment="All Saints day">Día de Todos los Santos</date>
	<date day="8" month="12" free="true" comment="Immaculate Conception">Inmaculada Concepción</date>
	<date day="9" month="12" free="true" comment="Battle of Ayacucho">Batalla de Ayacucho</date>
	<date day="25" month="12" free="true"	comment="Christmas Day">Navidad</date>
</holidays>

=== heiglandreas/holidayChecker/share/VE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://www.officeholidays.com/countries/venezuela" lastChecked="2025-02-12"/>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Venezuela" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true" comment="New Years Day">Día de Año Nuevo</date>
	<date day="6" month="1" free="false" comment="Epiphany, Banks closed">Día de Reyes</date>
	<easter offset="-48" free="true" comment="Carnival">Carnaval</easter>
	<easter offset="-47" free="true" comment="Carnival">Carnaval</easter>
	<date day="19" month="3" free="false" comment="St. Josephs Day, Banks closed">Día de San José</date>
	<easter offset="-6" free="false" comment="Holy Week, Public Sector usually free">Semana Santa</easter>
	<easter offset="-5" free="false" comment="Holy Week, Public Sector usually free">Semana Santa</easter>
	<easter offset="-4" free="false" comment="Holy Week, Public Sector usually free">Semana Santa</easter>
	<easter offset="-3" free="true" comment="Maundy Thursday">Semana Santa</easter>
	<easter offset="-2" free="true" comment="Good Friday">Semana Santa</easter>
	<date day="19" month="4" free="true" comment="Independence declaration day">Diecinueve de abril</date>
	<date day="1" month="5" free="true" comment="Labour Day">Día del Trabajador</date>
	<relative day="7" month="5" relation="next sunday" free="false" comment="Mothers day">Día de las Madres</relative>
	<relative day="14" month="6" relation="next sunday" free="false" comment="Fathers Day">Día de los Padres</relative>
	<easter offset="30" free="false" comment="Ascension Day, Banks only">Día de la ascención</easter>
	<easter offset="60" free="false" comment="Corpus Christi, banks only">Corpus Christi</easter>
	<date day="24" month="6" free="true" comment="St. Johns Day">Día de San Juan Bautista y Aniversario de la Batalla de Carabobo</date>
	<date day="29" month="6" free="true" comment="St Peter and Paul">Día de San Pedro y San Pablo</date>
	<date day="5" month="7" free="true" comment="Independence Day">Cinco de julio</date>
	<date day="24" month="7" free="true" comment="Birth of Simon Bolivar">Natalicio del Libertador</date>
	<date day="15" month="8" free="true" comment="Assumption Day">Día de la Asunción</date>
	<relative day="7" month="9" relation="next sunday" free="false" comment="Feast of our Lady of Coromoto, Banks closed">Aparicion del Virgen del Coromoto</relative>
	<date day="13" month="10" free="true" comment="Indigenous resistance day">Día de la Resistencia Indígena</date>
	<date day="3" month="11" free="true" comment="Al Saints Day">Día de Todos los Santos</date>
	<date day="8" month="12" free="false" comment="Immacualte COnception Day, Banks closed">Inmaculada Concepción</date>
	<date day="24" month="12" free="true"	comment="Christmas Eve">Nochebuena</date>
	<date day="25" month="12" free="true" comment="Christmas">Navidad</date>
	<date day="31" month="12" free="true" comment="New Years Eve">Nochevieja</date>
</holidays>

=== heiglandreas/holidayChecker/share/NL.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">Nieuwjaarsdag</date>
    <easter offset="-2" free="false">Goede Vrijdag</easter>
    <easter offset="1" free="true">Pasen</easter>
    <easter offset="0" free="false">Pasen</easter>
    <date day="27" month="4" free="true">Koningsdag</date>
    <date day="5" month="5" interval="5" firstobservance="1945" lastobservance="1990" free="true">Bevrijdingsdag</date>
    <date day="5" month="5" firstobservance="1990" free="true" restriction="paid free day only every 5 years">Bevrijdingsdag</date>
    <easter offset="40" free="true">Hemelvaartsdag</easter>
    <easter offset="49" free="true">Pinksteren</easter>
    <easter offset="50" free="true">Pinksteren</easter>
    <date day="5" month="12" free="false">Pakjesavond</date>
    <date day="25" month="12" free="true">Kerstmis</date>
    <date day="26" month="12" free="true">Kerstmis</date>
</holidays>
